<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Expression 2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Directives</string>
			<key>match</key>
			<string>@name|@inputs|@outputs|@persist|@trigger|@model</string>
			<key>name</key>
			<string>keyword.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Directives Parameters</string>
			<key>match</key>
			<string>(?&lt;=@name|@inputs|@outputs|@persist|@trigger|@model).+</string>
			<key>name</key>
			<string>variable.parameter.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#.+</string>
			<key>name</key>
			<string>comment.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Block Comment</string>
			<key>match</key>
			<string>#\[(.|\n|\r)*\]#</string>
			<key>name</key>
			<string>comment.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>if|elseif|else|return|while|switch|break|continue|function</string>
			<key>name</key>
			<string>keyword.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>match</key>
			<string>"(.*)"</string>
			<key>name</key>
			<string>string.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables</string>
			<key>match</key>
			<string>\b[A-Z]([a-zA-Z0-9]+)?</string>
			<key>name</key>
			<string>variable.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Functions Arguments</string>
			<key>match</key>
			<string>(?&lt;=function) [^() ]+</string>
			<key>name</key>
			<string>variable.parameter.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>\+|-|\*|/|:|\{|\}</string>
			<key>name</key>
			<string>keyword.source.expression2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Core Functions</string>
			<key>match</key>
			<string>\b[a-z]+[A-Za-z0-9]+</string>
			<key>name</key>
			<string>entity.name.function.source.expression2</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.expression2</string>
	<key>uuid</key>
	<string>1c9de391-9dbf-4fbc-9273-7e159b2f9830</string>
</dict>
</plist>
